### ISSUE TITLE
TypeError:state:path

### ISSUE THREAD

**Issue by ZZ-111** [robfiras/PandaAgents_RLBench#1]
First of all, thank you for sharing.
When I run python main.py,I got this error:
![12345](https://user-images.githubusercontent.com/55341540/94983918-634b6800-0579-11eb-86f8-c868c0c28ddc.png)
How to solve this problem.
Looking forward to your reply:)

**Comment by robfiras** [comment]
Hey!
Until now, you need to specify a path to a folder were weights are saved. 
A minimal example would be:
```shell
python main.py --log_dir /path/to/your/dir --save_weights
```
You can type `python main.py -h` for other stuff you can define.
